### ISSUE TITLE
listen EADDRINUSE: address already in use :::4500

### ISSUE THREAD

**Issue by alaherma** [OneCommunityGlobal/HGNRest#11]
i got the following error after running "npm start" in my local enviroment, im checked otu to master branch

> hgnrest@1.0.0 start C:\Users\Alvaro\HGN\HGNRest
> node dist/server.js

(node:3388) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Error: listen EADDRINUSE: address already in use :::4500
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at Function.listen (C:\Users\Alvaro\HGN\HGNRest\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\Users\Alvaro\HGN\HGNRest\dist\server.js:26:18)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hgnrest@1.0.0 start: `node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hgnrest@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alvaro\AppData\Roaming\npm-cache\_logs\2020-06-12T19_16_35_051Z-debug.log

**Comment by alaherma** [comment]
i had the back end already running , i just rebooted my pc, and this error no longer appears,
